
# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


# Switches
set_property PACKAGE_PIN V17 [get_ports {Switch0}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch0}]
set_property PACKAGE_PIN V16 [get_ports {Switch1}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch1}]
set_property PACKAGE_PIN W16 [get_ports {Switch2}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch2}]
set_property PACKAGE_PIN W17 [get_ports {Switch3}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch3}]
set_property PACKAGE_PIN W15 [get_ports {Switch4}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch4}]
set_property PACKAGE_PIN V15 [get_ports {Switch5}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch5}]
set_property PACKAGE_PIN W14 [get_ports {Switch6}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch6}]
set_property PACKAGE_PIN W13 [get_ports {Switch7}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch7}]
set_property PACKAGE_PIN V2 [get_ports {Switch8}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch8}]
set_property PACKAGE_PIN T3 [get_ports {Switch9}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch9}]
set_property PACKAGE_PIN T2 [get_ports {Switch10}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch10}]
set_property PACKAGE_PIN R3 [get_ports {Switch11}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch11}]
set_property PACKAGE_PIN W2 [get_ports {Switch12}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch12}]
set_property PACKAGE_PIN U1 [get_ports {Switch13}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch13}]
set_property PACKAGE_PIN T1 [get_ports {Switch14}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch14}]
set_property PACKAGE_PIN R2 [get_ports {Switch15}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switch15}]


# LEDs
set_property PACKAGE_PIN U16 [get_ports {L0}]
set_property IOSTANDARD LVCMOS33 [get_ports {L0}]
set_property PACKAGE_PIN E19 [get_ports {L1}]
set_property IOSTANDARD LVCMOS33 [get_ports {L1}]
set_property PACKAGE_PIN U19 [get_ports {L2}]
set_property IOSTANDARD LVCMOS33 [get_ports {L2}]
set_property PACKAGE_PIN V19 [get_ports {L3}]
set_property IOSTANDARD LVCMOS33 [get_ports {L3}]
set_property PACKAGE_PIN W18 [get_ports {L4}]
set_property IOSTANDARD LVCMOS33 [get_ports {L4}]
set_property PACKAGE_PIN U15 [get_ports {L5}]
set_property IOSTANDARD LVCMOS33 [get_ports {L5}]
set_property PACKAGE_PIN U14 [get_ports {L6}]
set_property IOSTANDARD LVCMOS33 [get_ports {L6}]
set_property PACKAGE_PIN V14 [get_ports {L7}]
set_property IOSTANDARD LVCMOS33 [get_ports {L7}]
set_property PACKAGE_PIN V13 [get_ports {L8}]
set_property IOSTANDARD LVCMOS33 [get_ports {L8}]
set_property PACKAGE_PIN V3 [get_ports {L9}]
set_property IOSTANDARD LVCMOS33 [get_ports {L9}]
set_property PACKAGE_PIN W3 [get_ports {L10}]
set_property IOSTANDARD LVCMOS33 [get_ports {L10}]
set_property PACKAGE_PIN U3 [get_ports {L11}]
set_property IOSTANDARD LVCMOS33 [get_ports {L11}]
set_property PACKAGE_PIN P3 [get_ports {L12}]
set_property IOSTANDARD LVCMOS33 [get_ports {L12}]
set_property PACKAGE_PIN N3 [get_ports {L13}]
set_property IOSTANDARD LVCMOS33 [get_ports {L13}]
set_property PACKAGE_PIN P1 [get_ports {L14}]
set_property IOSTANDARD LVCMOS33 [get_ports {L14}]
set_property PACKAGE_PIN L1 [get_ports {L15}]
set_property IOSTANDARD LVCMOS33 [get_ports {L15}]


# 7 segment display
set_property PACKAGE_PIN W7 [get_ports {topsegA}]
set_property IOSTANDARD LVCMOS33 [get_ports {topsegA}]
set_property PACKAGE_PIN W6 [get_ports {topsegB}]
set_property IOSTANDARD LVCMOS33 [get_ports {topsegB}]
set_property PACKAGE_PIN U8 [get_ports {topsegC}]
set_property IOSTANDARD LVCMOS33 [get_ports {topsegC}]
set_property PACKAGE_PIN V8 [get_ports {topsegD}]
set_property IOSTANDARD LVCMOS33 [get_ports {topsegD}]
set_property PACKAGE_PIN U5 [get_ports {topsegE}]
set_property IOSTANDARD LVCMOS33 [get_ports {topsegE}]
set_property PACKAGE_PIN V5 [get_ports {topsegF}]
set_property IOSTANDARD LVCMOS33 [get_ports {topsegF}]
set_property PACKAGE_PIN U7 [get_ports {topsegG}]
set_property IOSTANDARD LVCMOS33 [get_ports {topsegG}]


set_property PACKAGE_PIN U2 [get_ports {topselDispA}]
set_property IOSTANDARD LVCMOS33 [get_ports {topselDispA}]
set_property PACKAGE_PIN U4 [get_ports {topselDispB}]
set_property IOSTANDARD LVCMOS33 [get_ports {topselDispB}]
set_property PACKAGE_PIN V4 [get_ports {topselDispC}]
set_property IOSTANDARD LVCMOS33 [get_ports {topselDispC}]
set_property PACKAGE_PIN W4 [get_ports {topselDispD}]
set_property IOSTANDARD LVCMOS33 [get_ports {topselDispD}]


#Buttons
set_property PACKAGE_PIN U18 [get_ports Q]
set_property IOSTANDARD LVCMOS33 [get_ports Q]
set_property PACKAGE_PIN T18 [get_ports U]						
set_property IOSTANDARD LVCMOS33 [get_ports U]
set_property PACKAGE_PIN W19 [get_ports L]						
set_property IOSTANDARD LVCMOS33 [get_ports L]
set_property PACKAGE_PIN T17 [get_ports R]						
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property PACKAGE_PIN U17 [get_ports D]						
set_property IOSTANDARD LVCMOS33 [get_ports D]
